### ISSUE TITLE
iOS: Player is not renderering video - black screen

### ISSUE THREAD

**Issue by laurieattwobulls** [THEOplayer/samples-react-native#12]
Hi,

I am trying to get the sample (02 and 06) to run on iOS. ( Android works fine)
When I launch the sample app on the simulator or device, there is a black view covering the app. ~~Maybe the player not rendering the video?~~( see attachement) The player works fine on the iOS sample. So it has to be something with the react native bindings
The video is playing as I can hear the sound of the video.

Installation:
- at the root of the project (02 or 06), I start the react server
- I go in the ios folder
 - `>$ yarn`
 -  `>$ npx pod install`
 -  copy the iOS sdk into the ios folder
- at the root of the project (02 or 06)
 - `>$ yarn ios --simulator "iPhone 11"` (else I get an error because it doesn't find the iPhone X simulator which I don't have installed)

Actual result:
The player is not displaying the video, nor the player's UI.
![Simulator Screen Shot - iPhone 11 - 2020-11-05 at 18 16 46](https://user-images.githubusercontent.com/43458980/98210912-6af59680-1f95-11eb-86e5-eadece2871e0.png)

Note: When I produce an error to see if react is working fine, I do see an error and the react UI. 
![Simulator Screen Shot - iPhone 11 - 2020-11-05 at 18 16 40](https://user-images.githubusercontent.com/43458980/98210919-6c26c380-1f95-11eb-98d3-1969982e2f7c.png)

OS: MacOS Catalina 10.15.6
react-native-cli: 2.0.1
react-native: 0.61.2
XCode 12.1
yarn 1.22.10
npx pod 1.9.3

Thank you,

Laurie

**Comment by savdeepgandhi13** [comment]
We have investigated and found some items were added to info.plist which turned the screen to have multiple views. To solve the issue of the Black Screen, Solve by just removing in `Info.plist` file you have to remove `Application Scene Manifest` or just disable `Enable Multiple Windows`

<img width="689" alt="image001 (1)" src="https://user-images.githubusercontent.com/56595182/99978230-f9e01c80-2da5-11eb-8862-5274b174ddfd.png">
